Allow passing extra args to afl-cc
In some cases, extra args are needed for afl-cc to deal with dependencies.
Here is a direct error example:
```
/usr/bin/ld: /tmp/canonicalize_obj-627c31.o: in function `math.pow.pow__anon_19564':
/home/bren077s/vendor/zig-0.14.0/lib/std/math/pow.zig:140:(.text+0xbb09f): undefined reference to `exp'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: the following command exited with error code 1:
/usr/bin/afl-cc -O3 -o /home/bren077s/Projects/roc/.zig-cache/o/9ced3a0c7fc3d8ecae95995a20a187c8/canonicalize_obj /home/bren077s/Projects/roc-misc/zig-afl-kit/afl.c /home/bren077s/Projects/roc/.zig-cache/o/b709409d1b3458aad1bf84fea3f8f70a/canonicalize_obj.bc
```

It requires `-lm` to be added as an arg.